### Login User
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "afzal@mail.com",
    "password": "123456"
}

### Create User
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Afzal Hossain",
    "email": "afzal@mail.com",
    "password": "123456",
    "phone": "1200567100",
    "age": 36,
    "address": "123 Main St, City, Country"
}

### Get All Users
GET http://localhost:5000/users

### Get User by ID
GET http://localhost:5000/users/1

### Update User by ID
PUT http://localhost:5000/users/4
Content-Type: application/json

{
    "name": "Murad Hossain 22"
}

### Delete User by ID
DELETE http://localhost:5000/users/7

### Create Todo
POST http://localhost:5000/todos
Content-Type: application/json

{
    "user_id": 1,
    "title": "Finish Node.js project",
    "description": "Complete the CRUD operations for users and todos",
    "completed": false,
    "due_date": "2024-12-31"
}

### Get All Todos
GET http://localhost:5000/todos

### Get Todo by ID
GET http://localhost:5000/todos/1

### Update Todo by ID
PUT http://localhost:5000/todos/1
Content-Type: application/json

{
    "completed": true
}

### Delete Todo by ID
DELETE http://localhost:5000/todos/1